name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to Streamlit Cloud
      env:
        STREAMLIT_TOKEN: ${{ secrets.STREAMLIT_TOKEN }}
      run: |
        streamlit deploy main.py --name oda-sicakligi-dashboard
    
    - name: Update version
      run: |
        # Versiyon numarasını güncelle
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a v$(date +%Y.%m.%d) -m "Release $(date +%Y-%m-%d)"
        git push origin --tags
    
    - name: Generate changelog
      run: |
        # Changelog oluştur
        git log --pretty=format:"%h - %s (%an, %ar)" $(git describe --tags --abbrev=0)..HEAD > CHANGELOG.md
        git add CHANGELOG.md
        git commit -m "Update changelog"
        git push 